### PR TITLE
feat: initial datatable reactive values

### PR DESCRIPTION
**Pull request by aaronst**
For #1164, adds the [six reactive attributes listed in the docs](https://textual.textualize.io/widgets/data_table/#reactive-attributes) for `DataTable` to `__init__`. I noticed the class has three more reactive attributes (`cursor_type`, `cursor_cell`, and `hover_cell`) that aren't listed, but I left those out. Let me know if any of them should also be included.

### CODE REVIEW

**Review by willmcgugan — APPROVED** [review]

**Comment by darrenburns** [comment]
Something appears to have went horribly wrong with the tests. They were running for over 2 hours until I cancelled them.

**Comment by willmcgugan** [comment]
I've seen this all day. Github having a bad day maybe.

**Comment by darrenburns** [comment]
It seems like the snapshot tests have started hanging in CI, but not one in particular. Not sure what might've changed recently to cause this.

**Comment by willmcgugan** [comment]
Curious. I did merge some stuff to day.

**Comment by willmcgugan** [comment]
But the tests passed on everything I merged. And it seems to be working locally.

**Comment by darrenburns** [comment]
I think the stuff you seen earlier is different - they were failing, not hanging, right? I think the Windows ones can still fail sometimes because the delay at the end isn't long enough.

This PR is a different issue from what you've seen - it's consistently hanging on the `test_datatable_render` test on CI.

I've checked it out and it passes locally, but considering this PR touches the datatable and it's that test that's hanging, we'll need to work out why before merging this.

**Comment by aaronst** [comment]
After syncing this branch with `main`, I'm now getting the same hanging behavior when I try to test locally. I also see:

```
tests/test_table.py::test_table_clear FAILED                                                                                                               
tests/test_table.py::test_table_add_row FAILED
```

Not sure if related?

**Comment by willmcgugan** [comment]
Those were added recently. What’s the error?

**Comment by aaronst** [comment]
```
FAILED tests/test_table.py::test_table_clear - textual.css.query.NoMatches: No nodes match <DOMQuery TableApp(title='TableApp') filter='DataTable'>
FAILED tests/test_table.py::test_table_add_row - textual.css.query.NoMatches: No nodes match <DOMQuery TableApp(title='TableApp') filter='DataTable'>
```

Is what I see after `ctrl+c`.

**Comment by willmcgugan** [comment]
Up for a challenge. @aaronst ? Feels like it could be related to recent changes. The data table methods are new. But I can’t say what. 🤷‍♂️

**Comment by aaronst** [comment]
I'm on it!

**Comment by aaronst** [comment]
Was able to get this output by only running `test_table.py`:

```
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /Users/aaron/Documents/repos/textual/src/textual/app.py:1377 in _on_compose  │
│                                                                              │
│   1374 │                                                                     │
│   1375 │   async def _on_compose(self) -> None:                              │
│   1376 │   │   try:                                                          │
│ ❱ 1377 │   │   │   widgets = list(self.compose())                            │
│   1378 │   │   except TypeError as error:                                    │
│   1379 │   │   │   raise TypeError(                                          │
│   1380 │   │   │   │   f"{self!r} compose() returned an invalid response; {e │
│                                                                              │
│ ╭───────────── locals ──────────────╮                                        │
│ │ self = TableApp(title='TableApp') │                                        │
│ ╰───────────────────────────────────╯                                        │
│                                                                              │
│ /Users/aaron/Documents/repos/textual/tests/test_table.py:9 in compose        │
│                                                                              │
│    6                                                                         │
│    7 class TableApp(App):                                                    │
│    8 │   def compose(self) -> ComposeResult:                                 │
│ ❱  9 │   │   yield DataTable()                                               │
│   10                                                                         │
│   11                                                                         │
│   12 async def test_table_clear() -> None:                                   │
│                                                                              │
│ ╭───────────── locals ──────────────╮                                        │
│ │ self = TableApp(title='TableApp') │                                        │
│ ╰───────────────────────────────────╯                                        │
│                                                                              │
│ /Users/aaron/Documents/repos/textual/src/textual/widgets/_data_table.py:204  │
│ in __init__                                                                  │
│                                                                              │
│   201 │   ) -> None:                                                         │
│   202 │   │   super().__init__(name=name, id=id, classes=classes)            │
│   203 │   │                                                                  │
│ ❱ 204 │   │   self.show_header = show_header                                 │
│   205 │   │   self.fixed_rows = fixed_rows                                   │
│   206 │   │   self.fixed_columns = fixed_columns                             │
│   207 │   │   self.zebra_stripes = zebra_stripes                             │
│                                                                              │
│ ╭──────────────────────────── locals ─────────────────────────────╮          │
│ │     __class__ = <class 'textual.widgets._data_table.DataTable'> │          │
│ │       classes = None                                            │          │
│ │ fixed_columns = 0                                               │          │
│ │    fixed_rows = 0                                               │          │
│ │ header_height = 1                                               │          │
│ │            id = None                                            │          │
│ │          name = None                                            │          │
│ │          self = DataTable()                                     │          │
│ │   show_cursor = True                                            │          │
│ │   show_header = True                                            │          │
│ │ zebra_stripes = False                                           │          │
│ ╰─────────────────────────────────────────────────────────────────╯          │
│                                                                              │
│ /Users/aaron/Documents/repos/textual/src/textual/widgets/_data_table.py:263  │
│ in watch_show_header                                                         │
│                                                                              │
│   260 │   │   self.refresh()                                                 │
│   261 │                                                                      │
│   262 │   def watch_show_header(self, show_header: bool) -> None:            │
│ ❱ 263 │   │   self._clear_caches()                                           │
│   264 │                                                                      │
│   265 │   def watch_fixed_rows(self, fixed_rows: int) -> None:               │
│   266 │   │   self._clear_caches()                                           │
│                                                                              │
│ ╭───────── locals ──────────╮                                                │
│ │        self = DataTable() │                                                │
│ │ show_header = True        │                                                │
│ ╰───────────────────────────╯                                                │
│                                                                              │
│ /Users/aaron/Documents/repos/textual/src/textual/widgets/_data_table.py:248  │
│ in _clear_caches                                                             │
│                                                                              │
│   245 │   │   return self.cursor_cell.column                                 │
│   246 │                                                                      │
│   247 │   def _clear_caches(self) -> None:                                   │
│ ❱ 248 │   │   self._row_render_cache.clear()                                 │
│   249 │   │   self._cell_render_cache.clear()                                │
│   250 │   │   self._line_cache.clear()                                       │
│   251 │   │   self._styles_cache.clear()                                     │
│                                                                              │
│ ╭────── locals ──────╮                                                       │
│ │ self = DataTable() │                                                       │
│ ╰────────────────────╯                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'DataTable' object has no attribute '_row_render_cache'
```

So I put all the reactive attributes last and it seems happy now. But someone else will need to cancel and rerun the tests I think because the last one is still stuck.

**Comment by willmcgugan** [comment]
Thanks. I think we might have an issue where failed tests cause a deadlock, but that is something for us to solve.

**Pull request merged**
