### PR TITLE
fix(markdown): handle hard line breaks

### LINKED ISSUE #2058: Markdown renderer does not handle hard line breaks
I have a block of markdown (a so-called poem generated by chatgpt) that doesn't render properly in textual's markdown viewer. Here's a minimal program that shows the problem:
```py
from textual.app import App
from textual.widgets import MarkdownViewer

content = "In the world of social media,  \nWhere trends seem to come and go  \nThere's a symbol that stands out,  \nWith significance that continues to grow.  \n\n(2nd verse)"

class MyApp(App):
    def compose(self):
        yield MarkdownViewer(content)

MyApp().run()
```

By the CommonMark spec, the "<space><space><newline>" should be rendered as a hard line break: https://spec.commonmark.org/0.30/#hard-line-break
.. most markdown renderers, including the one in rich, do this.

```
# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.14.0 |
| Rich    | 13.3.2 |

## Python

| Name           | Value               |
|----------------|---------------------|
| Version        | 3.9.2               |
| Implementation | CPython             |
| Compiler       | GCC 10.2.1 20210110 |
| Executable     | /usr/bin/python3    |

## Operating System

| Name    | Value                                                      |
|---------|------------------------------------------------------------|
| System  | Linux                                                      |
| Release | 6.0.0-0.deb11.2-amd64                                      |
| Version | #1 SMP PREEMPT_DYNAMIC Debian 6.0.3-1~bpo11+1 (2022-10-29) |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | truecolor      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=80, height=24 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 80                  |
| is_terminal    | False               |
| encoding       | utf-8               |
| max_height     | 24                  |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |
```

textual markdown:
image

rich markdown:
image

gfm:
> In the world of social media,  
> Where trends seem to come and go  
> There's a symbol that stands out,  
> With significance that continues to grow.  
> 
> (2nd verse)

### PR DESCRIPTION
**Pull request by TomJGooding**
Fixes #2058. Seems too simple so sure I am missing something!

Sorry, not sure how to add tests.

### CODE REVIEW

**Comment by jepler** [comment]
Thanks! we found almost exactly the same fix -- I verified that your version fixes the problem I was seeing.

**Comment by TomJGooding** [comment]
I've moved this PR from draft to ready to review. There's no tests I'm afraid but even after looking back on other PRs I'm still not sure how your testing works.

**Review by willmcgugan — APPROVED** [review]

**Comment by willmcgugan** [comment]
Nice and simple.

We might do a snapshot test with some example markdown, but I think that's fine for now.

Thanks.

**Comment by TomJGooding** [comment]
Thanks Will - only hesitated submitting as wasn't sure if you required snapshot tests or not.

Any plans to add some contributing guidelines or you'd rather keep Textual "insular" for now?

**Comment by willmcgugan** [comment]
We could use some contributing guidelines. Wouldn't want to discourage PRs.

**Pull request merged**
