### PR TITLE
Loosen platformdirs version requirement

### PR DESCRIPTION
**Pull request by JaceyPenny**
**Please review the following checklist.**

- [ ] Docstrings on all new or modified functions / classes 
- [ ] Updated documentation
- [ ] Updated CHANGELOG.md (where appropriate)

See comment: https://github.com/Textualize/textual/pull/4875#issuecomment-2326882999

### CODE REVIEW

**Comment by JaceyPenny** [comment]
@darrenburns @willmcgugan hey guys, super sorry to bother! I am sure this isn't impacting your work so no worries nor rush on this, but if you have the time I'd much appreciate a review! Thanks for your time I appreciate it a lot.

**Comment by willmcgugan** [comment]
Hey @darrenburns I wonder if we can just vendor the relevant function and omit the dependency entirely?

**Comment by darrenburns** [comment]
I had a look but it wasn't very self-contained. It depended on lots of other functions for checking environments and os IIRC

**Comment by willmcgugan** [comment]
Fair enough. It's a fairly small dependency anyway.

**Comment by JaceyPenny** [comment]
Rebased and re-locked against `main`

**Comment by willmcgugan** [comment]
Thanks

**Pull request merged**
