### PR TITLE
Recode incoming text on Windows before input event processing

### PR DESCRIPTION
**Pull request by davep**
This is a tentative fix for #3178. I'm keeping this as draft for the moment as this affects the Windows input at a very low level, and I'd like the input of @darrenburns and @willmcgugan on if this makes sense. What I do know is that this fixes the problem reported in #3178, and so I suspect there's the core of the solution in here.

So... eyes and experience with handling emoji and the like on this would be welcome.

### CODE REVIEW

**Comment by davep** [comment]
Moving out of draft for full review [as per](https://github.com/Textualize/textual/issues/3178#issuecomment-1733209574).

**Comment by davep** [comment]
Merged in `main` as it's a couple of days since it was put into the review queue.

**Review by willmcgugan — APPROVED** [review]

**Comment by willmcgugan** [comment]
Would be awesome if you could find some reference in the win32 docs as to why this is required on Windows, and not elsewhere. But if this is the fix, lets merge.

**Comment by darrenburns** [comment]
I spotted a few references to data on the clipboard being encoded as UTF-16 on the MS developer docs, but nothing that stands out to explain exactly why the approach in this PR approach works.

e.g. https://learn.microsoft.com/en-us/dotnet/api/system.windows.clipboard.settext?view=windowsdesktop-7.0

**Pull request merged**
