### PR TITLE
fix(text area)!: stop escape shifting focus if default tab behaviour

### LINKED ISSUE #4110: `TextArea` still uses `Escape` to move focus on
While "out of the box" `TextArea` now uses <kbd>Tab</kbd> to shift focus, it also still uses <kbd>Escape</kbd>, ideally it would not when in this mode. Pressing <kbd>Escape</kbd> to exit a modal dialog would be common, so having <kbd>Escape</kbd> do something different given one particular widget type would be surprising for the user.

For example, this dialog uses <kbd>Escape</kbd> as the quick exit key, but instead if moves focus if you happen to press it while in the `TextArea`:

Screenshot 2024-02-02 at 21 18 15

### PR DESCRIPTION
**Pull request by TomJGooding**
Fixes #4110.

**Please review the following checklist.**

- [ ] Docstrings on all new or modified functions / classes 
- [x] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

### CODE REVIEW

**Review by darrenburns — APPROVED** [review]
One small suggestion, but looks good. Thanks!

**Comment by darrenburns** [comment]
Also, for the CHANGELOG I think it'll go into the "Fixed" section, and noted as a breaking change.

**Comment by TomJGooding** [comment]
Done - I struggling with wording the changelog entry so hope that is okay!

(Also fixed where it looks like the changelog was out-of-sync after latest update)

**Comment by darrenburns** [comment]
Thanks!

**Pull request merged**
