### PR TITLE
Fix Toggle Buttons on a selection list

### PR DESCRIPTION
**Pull request by dmunozv04**
**Please review the following checklist.**

- [ ] Docstrings on all new or modified functions / classes 
- [ ] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

### CODE REVIEW

**Comment by dmunozv04** [comment]
This PR makes the Toggle Buttons on a selection list clickable/hoverable by adding the style meta option property

**Comment by davep** [comment]
Good catch. Would you mind adding a CHANGELOG entry to that effect too?

I sense we should also add an extra unit test or two to ensure that clicking on the checkbox has the desired effect (I'm happy to help with that if you're not familiar with adding tests to Textual).

**Comment by dmunozv04** [comment]
As I’m not familiar with adding tests, I’d appreciate getting help on doing that

**Comment by davep** [comment]
> I’ve updated the changelog

Thanks.

> As I’m not familiar with adding tests, I’d appreciate getting help on doing that

No worries; when I get a moment I'll add an appropriate test for this.

**Comment by davep** [comment]
Right, that all looks like it's going through okay; I'll see about adding the extra test in the morning.

Thanks again for this @dmunozv04 -- good spot!

**Comment by davep** [comment]
Tests added; as I've added code to this too I've requested review from the rest of the team.

**Review by willmcgugan — APPROVED** [review]

**Pull request merged**
