### PR TITLE
Mark the command palette as existing

### PR DESCRIPTION
**Pull request by davep**
I've not checked off "Command menu" as that sounds like something slightly different from the command palette.

### CODE REVIEW

**Comment by TomJGooding** [comment]
Mark as existing... or M-x for short?

**Comment by willmcgugan** [comment]
That's it. We're going to have an emacs jar. Whenever somebody mentions anything re emacs they have to deposit £1 in the jar.

Pretty soon we won't need VC money!

**Comment by willmcgugan** [comment]
I think we could probably replace that section with just "Command Palette" and check it off. Don't recall what I had in mind with "command menu"

**Comment by davep** [comment]
Roadmap tweaked.

**Review by willmcgugan — APPROVED** [review]

**Pull request merged**
