### PR TITLE
context sensitive help

### PR DESCRIPTION
**Pull request by willmcgugan**
- Adds widget help to the help panel (previously the "key panel").
  DOMNodes now have a `HELP` classvar which may be set to Markdown that renders in the help panel.
- Removes some jankiness when summoning the command palette.

Screenshot 2024-08-21 at 13 33 27

### CODE REVIEW

**Comment by darrenburns** [comment]
Should the sidebar have a title of "Help", or the name of the widget that the help is being displayed for? Or customisable? Or nothing? 😄

**Comment by darrenburns** [comment]
This looks good to me but I think I'd want a title personally (which could always be hidden with `display: none`) and also some way of controlling it with the keyboard.

**Comment by willmcgugan** [comment]
The title of the widget is shown above the top group of keys.

I don't think it looks good with a title. Seems redundant, and it takes up 2 lines.

Agree about keyboard control, but I'll do that in another pass.

Screenshot 2024-08-22 at 10 42 33

**Comment by willmcgugan** [comment]
How about this?

https://github.com/user-attachments/assets/9003594e-ca17-4f9e-99fc-3a04a41f1f13

**Comment by darrenburns** [comment]
I agree it doesn't look great there! Maybe you're right 😄

**Comment by willmcgugan** [comment]
How about I hide it by default. And if a dev asks, they can unhide it?

**Comment by darrenburns** [comment]
Seems like a reasonable compromise.

**Comment by darrenburns** [comment]
Could you add a snapshot test? After that it LGTM.

**Review by darrenburns — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
