### PR TITLE
Revert retrofitting of example code in an old blog post

### PR DESCRIPTION
**Pull request by davep**
Makes sense to update all the docs to reflect the work done in #1738 but I feel it doesn't quite make sense to retrofit this into an old blog post -- especially if the code it is referring to was like that at the time and likely still will be for a wee while after this gets republished.

### CODE REVIEW

**Comment by rodrigogiraoserrao** [comment]
Apologies! I thought it made sense to do the change but if the blog post refers explicitly the textual version it was written for, I think your reversal makes sense.

**Review by rodrigogiraoserrao — APPROVED** [review]

**Review by willmcgugan — APPROVED** [review]
Makes sense to keep a historical record in the blog.

**Comment by willmcgugan** [comment]
In the unlikely event that confuses people, I suggest we add some kind of admonition. Like "This has changed since the this post was published".

**Comment by davep** [comment]
> Apologies! I thought it made sense to do the change but if the blog post refers explicitly the textual version it was written for, I think your reversal makes sense.

Ahh, no apologies needed; it's an either/or call there I'd say. Your call on it made perfect sense. :-)

**Comment by davep** [comment]
> In the unlikely event that confuses people, I suggest we add some kind of admonition. Like "This has changed since the this post was published". 

I like this. I'll likely do that once it's all settled.

**Pull request merged**
