### PR TITLE
docs(tutorial): Add chinese translation for tutorial

### PR DESCRIPTION
**Pull request by 100gle**
@willmcgugan Textual is an interesting and powerful project, I love it and hope every python users can enjoy it. 

So today I add a **chinese** translation for tutorial docs, if there is any plan for document translation, hope this PR can be helpful.

### CODE REVIEW

**Comment by willmcgugan** [comment]
谢谢你!

Will look at this soon. Still need to look in to our internationalization solution.

**Comment by 100gle** [comment]
> 谢谢你!
> 
> Will look at this soon. Still need to look in to our internationalization solution.

Just a little bit of contribution, don't mention it. 

If there is any translation plan for chinese docs, I can do my pleasure. XD

**Comment by davep** [comment]
Hey @100gle, just realised this has been sat around for a long while and not merged. We really appreciate the effort, and would absolutely welcome a translation of the tutorial (and hopefully in time all of the documentation). However, as you may have noticed, Textual is still in heavy development with lots of things constantly changing. This is going to make it quite a moving target for anyone doing translation work.

Would you mind if we closed this PR for now, and perhaps come back to this once things are more stable?

**Comment by 100gle** [comment]
@davep 

Never mind. I have learnt how to use textual when translation. Just do you want. :)

**Pull request closed without merging**
