### PR TITLE
Improve event loop handling around run_app

### PR DESCRIPTION
**Pull request by bsdz**
- [x] Docstrings on all new or modified functions / classes 
- [ ] Updated documentation
- [ ] Updated CHANGELOG.md (where appropriate)

This resolves issue #615 as it also occurs in Panel which embeds a memray app that utilizes textual.

### CODE REVIEW

**Comment by willmcgugan** [comment]
This looks like it would be implementing [`run_async`](https://textual.textualize.io/api/app/#textual.app.App.run_async), which is the recommended way of integrating Textual with an existing loop.

**Comment by bsdz** [comment]
> This looks like it would be implementing [`run_async`](https://textual.textualize.io/api/app/#textual.app.App.run_async), which is the recommended way of integrating Textual with an existing loop.

I see. Is the issue then, how memray integrates with textual?

**Comment by willmcgugan** [comment]
> I see. Is the issue then, how memray integrates with textual?

Potentially, but I'm not clear on what the issue is. Can you provide me with more information on what you are doing and the error you are getting?

**Comment by bsdz** [comment]
> > I see. Is the issue then, how memray integrates with textual?
> 
> Potentially, but I'm not clear on what the issue is. Can you provide me with more information on what you are doing and the error you are getting?

I was trying to use [Holviz Panel's builtin profiler](https://panel.holoviz.org/how_to/profiling/profile.html). One profiler option in Panel is to use [memray](https://github.com/bloomberg/memray). Panel is able to embed various web based components within a unified framework. The profilers are embeded as web components under the admin panel within Panel. It seems that this worked for memray version 1.10.0 (discovered after some investigation). Since [memray 1.11.0](https://github.com/bloomberg/memray/releases/tag/v1.11.0), textual must have replaced the web components of memray and when one tries to use this version of memray in panel, it fails with the above error. Hence my PR. All that said, it seems even with the above change in code, memray 1.11.0 still doesn't work in Panel. I've now switched to memray 1.10.0 and this seems to help (although not perfectly).

**Comment by willmcgugan** [comment]
You may want to raise this issue with the memray devs. I'm sure there is a simple workaround.

**Comment by bsdz** [comment]
> You may want to raise this issue with the memray devs. I'm sure there is a simple workaround.

That's fine, although I'd recommend changing your code too (as suggested in my PR). The python docs recommend using [get_running_loop](https://docs.python.org/release/3.12.1/library/asyncio-eventloop.html?highlight=get_running_loop#asyncio.get_event_loop) and my proposed approach is similar to that [suggested here](https://stackoverflow.com/a/61331974/370696).

**Pull request closed without merging**
