### PR TITLE
fixes #2991 by adjusting the y scroll after max_lines exceeded

### LINKED ISSUE #2991: TextLog auto_scroll = False doesn't work as intended if max_lines exceeded
If the amount of text in a TextLog hits max_lines, and the user scrolls back, their viewport will scroll forward as new content is added.

Here's an example where I page up, setting auto_scroll=False.

scroll

As new content is added, the point on the scrollbar stays constant, but the content changes.  With auto_scroll = False, I would expect the viewport to remain constant and the scroll bar point to continually get further back, until we reach the edge of history where that is no longer possible.

Screen grab from textual 0.30.0.

### PR DESCRIPTION
**Pull request by mardanst**
**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- [x] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

### CODE REVIEW

**Comment by rodrigogiraoserrao** [comment]
Hey @mardanst, thanks for the PR.

Before we take a look at it, could you make sure the tests pass locally?
You can go through the steps outlined in #2923, from the section "Guidelines" onwards.
Thanks!

**Comment by mardanst** [comment]
That link was very helpful.  I was able to fix the failing test and add a new snapshot test for #2991 .  

Tests are passing locally, but failing in github on (windows-latest,3.11) on an unrelated test.

**Comment by mardanst** [comment]
Resubmitted it and it passed the second time through

**Comment by rodrigogiraoserrao** [comment]
Thanks for following up on it. We'll take a look and get back to you.

As you realised, some of our tests are a bit flakey. When one of those fails, no need to create a "fake" commit to trigger them again. We'll rerun them for you :)

**Comment by willmcgugan** [comment]
Closing, assumed stale. I don't think the issue is still present.

**Pull request closed without merging**
