### PR TITLE
fix(markdown): render softbreak split links

### LINKED ISSUE #2805: Rendered Markdown links are broken into chunks when source text is multi-line
## Current behaviour

When a link in Markdown is split over two or more lines, the rendered link will be "broken" and not continue through the whitespace created for each of those broken lines.

Given the Markdown document:

```
My site [has
this
URL](https://example.com)
```

When we run that on [markdown-it](https://markdown-it.github.io/) it renders as a "single link" (sorry mouse disappeared when triggering screenshot):

Screenshot 2023-06-19 at 15 04 15

However, when embedding that document into the [Markdown widget `markdown.py` example](https://textual.textualize.io/widgets/markdown/#__tabbed_1_2) from the docs as follows:

```py
from textual.app import App, ComposeResult
from textual.widgets import Markdown

EXAMPLE_MARKDOWN = """\
My site [has
this
URL](https://example.com)
"""


class MarkdownExampleApp(App):
    def compose(self) -> ComposeResult:
        yield Markdown(EXAMPLE_MARKDOWN)


if __name__ == "__main__":
    app = MarkdownExampleApp()
    app.run()
```

Then running with `python markdown.py` gives the following render - where you can see the link is "broken" to appear as 3 items:

Screenshot from 2023-06-19 15-07-27

And on hover:

Screenshot from 2023-06-19 15-07-39

One subtle issue I've found with this bug, is when I hover over the white space gaps, the link does _not_ highlight 😞 

## Expected behaviour

Link is expected to render the same as if it was on a single line in the Markdown file:

Screenshot from 2023-06-19 15-08-44

## Debug info...

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.28.0 |
| Rich    | 13.4.2 |

## Python

| Name           | Value                                  |
|----------------|----------------------------------------|
| Version        | 3.11.0                                 |
| Implementation | CPython                                |
| Compiler       | GCC 9.4.0                              |
| Executable     | /tmp/tmp.E7iYfjTaVi/venv311/bin/python |

## Operating System

| Name    | Value                                              |
|---------|----------------------------------------------------|
| System  | Linux                                              |
| Release | 5.15.0-75-generic                                  |
| Version | #82~20.04.1-Ubuntu SMP Wed Jun 7 19:37:37 UTC 2023 |

## Terminal

| Name                 | Value           |
|----------------------|-----------------|
| Terminal Application | *Unknown*       |
| TERM                 | screen-256color |
| COLORTERM            | truecolor       |
| FORCE_COLOR          | *Not set*       |
| NO_COLOR             | *Not set*       |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=105, height=58 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 105                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 58                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

Sorry no kittens in this bug report 🙏🏻

### PR DESCRIPTION
**Pull request by TomJGooding**
Fixes #2805.

Currently a link split over several lines is not rendered correctly in `Markdown`, as the softbreak tokens are parsed only as spaces without any Rich styling.

**Example markdown:**

```
My site [has
this
URL](https://example.com)
```

**Screenshot:**

Screenshot from 2023-06-19 15-07-27

**Rich `Text` object:**

```python
<text 'My site has this URL' [
    Span(0, 8, Style()), 
    Span(8, 11, Style(meta={'@click': "link('https://example.com')"})), 
    Span(12, 16, Style(meta={'@click': "link('https://example.com')"})), 
    Span(17, 20, Style(meta={'@click': "link('https://example.com')"}))
]>
```

Here's the Text object after the fix suggested in this PR, where the spaces at indices 11 and 16 also have the link styling applied:

```python
<text 'My site has this URL' [
    Span(0, 8, Style()), 
    Span(8, 11, Style(meta={'@click': "link('https://example.com')"})), 
    Span(11, 12, Style(meta={'@click': "link('https://example.com')"})), 
    Span(12, 16, Style(meta={'@click': "link('https://example.com')"})), 
    Span(16, 17, Style(meta={'@click': "link('https://example.com')"})), 
    Span(17, 20, Style(meta={'@click': "link('https://example.com')"}))
]>
```

### CODE REVIEW

**Comment by willmcgugan** [comment]
Thanks, Tom! Any chance of a test?

**Comment by TomJGooding** [comment]
Sorry Will, I would need a bit of guidance to add a test for this.

**Comment by willmcgugan** [comment]
Hmm. Doesn't look straightforward to test. I think it might require a small refactor.

I wonder if you could extract the code that accepts markdown and returns a list of widgets. That way you could run it in a test, and inspect the output.

Let me know if you want to tackle that. Also happy to merge and we can add a test in another update...

**Comment by TomJGooding** [comment]
Hi Will, I did make a start on creating a test for this last night, see below. I'll add a commit if you're happy with that, or let me know if you'd prefer your approach.

```python
async def test_softbreak_split_links_rendered_correctly() -> None:
    """Test for https://github.com/Textualize/textual/issues/2805"""

    document = """\
My site [has
this
URL](https://example.com)\
"""
    async with MarkdownApp(document).run_test() as pilot:
        markdown = pilot.app.query_one(Markdown)
        paragraph = markdown.children[0]
        assert isinstance(paragraph, MD.MarkdownParagraph)
        assert paragraph._text.plain == "My site has this URL"
        expected_spans = [
            Span(0, 8, Style()),
            Span(8, 11, Style(meta={"@click": "link('https://example.com')"})),
            Span(11, 12, Style(meta={"@click": "link('https://example.com')"})),
            Span(12, 16, Style(meta={"@click": "link('https://example.com')"})),
            Span(16, 17, Style(meta={"@click": "link('https://example.com')"})),
            Span(17, 20, Style(meta={"@click": "link('https://example.com')"})),
        ]
        assert paragraph._text.spans == expected_spans
```

**Comment by willmcgugan** [comment]
Yeah, I think that also works!

**Comment by TomJGooding** [comment]
Sorry I shouldn't have force pushed that last commit. Maybe I should just stay in my lane for non-trivial PRs - let me know how I can help fix it if needed.

**Comment by willmcgugan** [comment]
@TomJGooding This looks good to me. The PR is marked as draft, are you still working on it?

**Comment by TomJGooding** [comment]
Hey Will, sorry I marked this as draft after realising I'd forced pushed that last commit and wanted to make sure this wasn't going to cause any issues merging. Blame my lack of experience with [how git actually works](https://xkcd.com/1597/).

**Comment by willmcgugan** [comment]
No worries. Nobody really knows how git works.

**Review by willmcgugan — APPROVED** [review]

**Pull request merged**
