### PR TITLE
Filter out any NUL keystrokes that aren't Ctrl+2/Ctrl+space

### PR DESCRIPTION
**Pull request by davep**
See #872.

### CODE REVIEW

**Comment by davep** [comment]
Note that this also solves the problem of the Command Palette popping up when you paste something into an input field in Windows.

**Comment by davep** [comment]
Taking this back to draft for a moment. While it seems to work fine in Windows under Parallels on my Mac, it's not working fine on the native Windows installation. This *might* be down to Windows Terminal version or something, amongst other things, so I want to double-check all of that.

**Comment by davep** [comment]
Key differences between working and non-working environments:

# Working

- Windows 11
- Under Parallels
- Under macOS
- Windows Terminal 1.17.11461.0

# Non-working

- Windows 10 Pro
- Native
- Windows Terminal 1.16.10261.0

# Conclusion

The first thing to try is to update the version of Windows Terminal so it's the same in both places.

**Comment by davep** [comment]
Updated to the same version of Windows Terminal, on the native Windows 10 machine, and it made not a jot of difference. I'll throw in some low-level debugging again to see what's coming through.

The machine also has the option to be upgraded to Windows 11, but I'm not going to jump into doing that just yet -- having a Windows 10 machine to hand to test with does make a lot of sense; especially if that is the difference.

**Comment by davep** [comment]
https://github.com/microsoft/terminal/issues/2865 may be important here.

**Comment by davep** [comment]
Even odder. This PR, under Windows 11, under Parallels, on macOS, still supports <kbd>Ctrl</kbd>+<kbd>Space</kbd>. OTOH @rodrigogiraoserrao reports that Windows 11 native, with this PR, shows nothing for the same key combination; while at the same time without the PR shows `ctrl+@`.

**Comment by TomJGooding** [comment]
I've also been doing some testing on my Windows 10 if it helps.

Running `textual keys` on main and then pressing `ctrl` on its own shows 'ctrl+@'. Pressing `ctrl+space` results in 'ctrl+@ showing twice.

With this PR, `textual keys` shows nothing both after pressing `ctrl` and `ctrl+space`.

**Comment by davep** [comment]
@TomJGooding Thanks, looks like you're seeing what I'm seeing.

**Comment by davep** [comment]
So, having tested native on Windows 11 here too now, and seeing the same effect, this little hack doesn't quite solve the problem at all. Or, more to the point: it *does* seem to solve the problem but at the expense of <kbd>Ctrl</kbd>+<kbd>Space</kbd>; this might be an acceptable loss if #872 is a bigger problem.

I'm going to leave this as draft while we think on this and explore other options. Meanwhile we'll move the Command Palette onto a different keyboard combination that we can be more confident about.

**Comment by TomJGooding** [comment]
> AKA, for when I can handle subjecting myself to opening a Windows session again and having to try and do Python coding in the most hostile of environments.

I guess even if you had Emacs you couldn't set a mark either.... :wink:

**Comment by davep** [comment]
> I guess even if you had Emacs you couldn't set a mark either.... 😉

<kbd>M</kbd>-<kbd>x</kbd> `set-mark-command` <kbd>RET</kbd> :-P

**Comment by TomJGooding** [comment]
You may have found this already, but I stumbled on the [debug tap](https://github.com/microsoft/terminal/wiki/Toubleshooting-Tips#enabling-the-debug-tap) mode for Windows Terminal which might be useful?

**Comment by davep** [comment]
Closing this PR as it seems the downsides outweigh how trivial it is, and hopefully there's a more fundamental solution to be had with something like #3411.

**Pull request closed without merging**
