### PR TITLE
[WIP] widgets: new "TextArea" widget

### PR DESCRIPTION
**Pull request by 0x42656E**
**Note:**
- the following widget is still in the early stages of development and is **far** from being ready for production
- feel free to request/make changes to improve the code.

### Description
Compared to the "Input" widget, the "TextArea" widget makes it possible to edit text on multiple lines.

So far the widget offers:
- a cursor that can be moved vertically and horizontally
- the insertion of characters (including line breaks)
- character deletion (including line breaks)
- syntax highlighting using `Syntax` from `rich.syntax`.
- horizontal and vertical scrolling when the text goes out of the bounds of the screen

here a [demo](https://discord.com/channels/1026214085173461072/1033752599112994867/1110264382421745745) :slightly_smiling_face:

### CODE REVIEW

**Comment by willmcgugan** [comment]
@0x42656E This looks amazing. Building a textarea is a challenge, and probably the most sophisticated widget we will ever need.

We were planning to build a Textarea that uses the line API. We have some specific requirements that we need out of that. I'm not sure if we would be able to add your implementation to the core lib. You might want to consider building it as an external library.

Please keep us updated with your progress! And let is know if we can help in any way.

**Comment by 0x42656E** [comment]
Hi @willmcguganm, first of all thank you for your answer. Is there already a document or discussion where these requirements for the textarea widget are discussed/written down? 
Since I'm still a newbie in the textual universe, the PR doesn't need to be in the core lib, it's more important to me to reach the community/textual core devs.  :slightly_smiling_face: .

**Comment by 0x42656E** [comment]
@willmcgugan sounds cool. thank u

**Comment by Menschomat** [comment]
Hey @0x42656E , I'm currently starting to build a postman-like rest-client application for the command-line.
It would be really nice if you add some readme/documentation to you text_area-project.

**Comment by 0x42656E** [comment]
@Menschomat Hi, i'm not working on this project anymore. As far as I know, the textual team is currently building their own "textarea" widget (here is the related branch -> https://github.com/Textualize/textual/tree/text-area ), which will be realized with the help of the tree sitter project. Please note that the text area widget is still under development. 
If you don't want to wait for that, this project provides a working textarea widget -> https://github.com/tconbeer/textual-textarea. Have a good day! :slightly_smiling_face:

**Comment by Menschomat** [comment]
Thank you very much for the good summary of options 🙂

**Pull request closed without merging**
