### PR TITLE
Testing guide

### PR DESCRIPTION
**Pull request by brokenshield**
**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- [x] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

### CODE REVIEW

**Comment by brokenshield** [comment]
I made a set of minor grammar and consistency tweaks to the testing.md file. This is my first pull request ever, so hopefully I've performed it correctly!

**Comment by davep** [comment]
Given the PR for the guide hasn't been reviewed or merged yet, it might make more sense to feedback what you saw in the PR itself: #3329 (this likely explains why your PR seems to be a duplicate of #3329 with some extra changes)

**Comment by brokenshield** [comment]
> Given the PR for the guide hasn't been reviewed or merged yet, it might make more sense to feedback what you saw in the PR itself: #3329 (this likely explains why your PR seems to be a duplicate of #3329 with some extra changes)

Sure, I'm happy to do that. How would you like me to present the feedback? Shall I attach the file here?

**Comment by willmcgugan** [comment]
> > Given the PR for the guide hasn't been reviewed or merged yet, it might make more sense to feedback what you saw in the PR itself: #3329 (this likely explains why your PR seems to be a duplicate of #3329 with some extra changes)
> 
> Sure, I'm happy to do that. How would you like me to present the feedback? Shall I attach the file here? Will asked me to take a look at the file and so I did so as a PR. Apologies if I did that wrong :)

GitHub has a nice comment and suggestion feature. You can click on a line and add a comment. You can also click the suggestion button to offer a suggestion. Suggestions are great because you can accept them with a click of a button.

Here's a short video to demo that....

https://github.com/Textualize/textual/assets/554369/e681c665-72c2-4f7d-b4f4-e65b61fdd5de

It would be great if you could do that on https://github.com/Textualize/textual/pull/3329

**Comment by brokenshield** [comment]
> > > Given the PR for the guide hasn't been reviewed or merged yet, it might make more sense to feedback what you saw in the PR itself: #3329 (this likely explains why your PR seems to be a duplicate of #3329 with some extra changes)
> > 
> > 
> > Sure, I'm happy to do that. How would you like me to present the feedback? Shall I attach the file here? Will asked me to take a look at the file and so I did so as a PR. Apologies if I did that wrong :)
> 
> GitHub has a nice comment and suggestion feature. You can click on a line and add a comment. You can also click the suggestion button to offer a suggestion. Suggestions are great because you can accept them with a click of a button.
> 
> Here's a short video to demo that....
> Screen.Recording.2023-09-16.at.22.36.55.mov
> 
> It would be great if you could do that on #3329

Will do that now! :)

**Comment by willmcgugan** [comment]
Cheers. No rush BTW!

**Comment by brokenshield** [comment]
> Cheers. No rush BTW!

Ok, I think I've one that? Hopefully, all is good. :D

**Comment by davep** [comment]
@brokenshield Thanks for doing that. Given you contributed these changes to the original PR, I'll close this one.

**Pull request closed without merging**
