### PR TITLE
Improved Windows Driver

### PR DESCRIPTION
**Pull request by EpicCodeWizard**
Fixes the cursor problem on `Powershell` and printing problem on all consoles. Now works (without glitches) on `Powershell`, `Cygwin`, and `Windows Terminal`. Note: `VSCode/Atom Terminals` only send key presses to python, not cursor positions, scrolling, etc.

### CODE REVIEW

**Comment by willmcgugan** [comment]
How old are you @EpicCodeWizard ?

**Comment by EpicCodeWizard** [comment]
I would rather not reveal my age, but I will say I haven't graduated yet.

**Comment by tusharsadhwani** [comment]
@willmcgugan what's the rationale for that question 🤣 seems out of the blue

**Comment by willmcgugan** [comment]
@EpicCodeWizard I appreciate you're trying to help, but your contributions haven't been all that helpful. 

I'd suggest keep watching the repos, and jump in on discussions if you like, but maybe avoid issues and PRs for a while.  At least util you have a bit more experience with coding.

You may also want to be careful about how you phrase things. Your posts gives the distinct impression that you developed the window driver. I'm sure that wasn't intentional, but its not a good look.

Thanks for your interest in Textual!

**Comment by EpicCodeWizard** [comment]
Thank you for your feedback. I'm extremely sorry for the inconvenience.

**Pull request closed without merging**
