### PR TITLE
Fix highlighted lines in docs example

### LINKED ISSUE #3902: Broken markup in style reference for visibility
See the `visibility_container.tcss` tab

https://textual.textualize.io/styles/visibility/#__tabbed_2_3

### PR DESCRIPTION
**Pull request by rodrigogiraoserrao**
Fix #3902

### CODE REVIEW

**Comment by willmcgugan** [comment]
Can you also fix the annotations.

**Comment by rodrigogiraoserrao** [comment]
I can't, no.

I've tried changing the type of annotation to the simple one (without `!`).
I've tried changing the spacing between annotations.
I've tried removing different annotations to see if one specific one was breaking things.
I've tried reintroducing the annotations one by one.

In principle, the annotations are OK but docs are building wrong.

Seems to be some sort of bug with the docs tooling as I've identified other places where they're funny:

 - https://textual.textualize.io/styles/border_subtitle_align/#__tabbed_2_3
 - https://textual.textualize.io/styles/border_title_align/#__tabbed_2_3

I'm going to identify the plugin/tool that provides this functionality and figure out if there have been bug reports about this.

**Comment by rodrigogiraoserrao** [comment]
Feel free to merge this fix to the highlighted lines and then a follow-up PR will take care of the annotations in this and the other examples.

**Comment by rodrigogiraoserrao** [comment]
Opened #3906 to keep track of the non-rendered annotations.

**Comment by willmcgugan** [comment]
I think I'd we can't do it properly in tcss we should just replace them with comments.

**Comment by rodrigogiraoserrao** [comment]
> I think I'd we can't do it properly in tcss we should just replace them with comments.

It _can_ be done in tcss: https://textual.textualize.io/styles/height/#__tabbed_2_3

**Comment by rodrigogiraoserrao** [comment]
We just need to investigate what's happening.

**Comment by willmcgugan** [comment]
Are you seeing the same thing as me? It's removing the `/*` but leaving in the `*/`. Which looks the the syntax is all wrong. If we can't fix that, then we can just use comments.

**Comment by rodrigogiraoserrao** [comment]
> Are you seeing the same thing as me? It's removing the `/*` but leaving in the `*/`. Which looks the the syntax is all wrong. If we can't fix that, then we can just use comments.

Ah, you only noticed that now?
The trailing `*/` has been there since I can remember and I _think_ mkdocs (or the tool that provides this feature) has a bug report open to fix it.

I thought you were talking about the `/* (n) */` that aren't being parsed / used to create annotations.

**Comment by rodrigogiraoserrao** [comment]
In that case, do you want to get rid of all of the `/* (n) */` in CSS files and use normal comments instead?

**Comment by willmcgugan** [comment]
Yeah, its a shame. But it could be confusing, so lets replace just the tcss annotations with simple comments.

**Comment by TomJGooding** [comment]
Sorry to stick my nose in (as usual!) but I _think_ changing to single-line comments and ensuring they aren't on the same line as the selector might fix this - see https://github.com/Textualize/textual/issues/3906#issuecomment-1863117627

**Comment by rodrigogiraoserrao** [comment]
I confirm Tom's findings, both.

If we change all listings from `sass` to `css`, annotations will work as expected and there will be no leftover `*/`.

If we _really_ want to keep listings as `sass`, then we can use `//` comments but that would require modifying Textual to allow `//` comments in TCSS.

**Comment by rodrigogiraoserrao** [comment]
I suppose we want to go with the option of changing code listings from `sass` to `css`..?

**Comment by TomJGooding** [comment]
> ...but that would require modifying Textual to allow `//` comments in TCSS.

Oops, sorry yeah I should have checked this was actually valid in TCSS! :facepalm:

**Comment by rodrigogiraoserrao** [comment]
I've went ahead and replaced all sass with css listings.
The only place I didn't do it was in blog posts.

**Review by davep — APPROVED** [review]
I've not checked every single thing that was modified, but a random sample looks good to me.

**Pull request merged**
