### PR TITLE
DirectoryTree: remove example code as examples/code_browser.py already covers that

### PR DESCRIPTION
**Pull request by 1ace**
We're not all lucky enough to be @willmcgugan :stuck_out_tongue_winking_eye:

### CODE REVIEW

**Comment by 1ace** [comment]
I had that fix lying around for ages and just posted it, but actually even with that it's still broken now.

I'll try fixing it properly; closing for now

**Comment by willmcgugan** [comment]
That was test code, which should probably just be removed. Were you trying to get `python -m textual.widgets._directory_tree` to work?

**Comment by 1ace** [comment]
Yeah, `python -m textual.widgets._directory_tree` is how I was using that.

It was actually easy to fix, so re-opening with that, but perhaps it should be moved into `examples/` instead?

**Comment by 1ace** [comment]
Added a commit to move the example code to `examples/tree.py`, and changed the `$HOME` to `.` as it should be a smaller folder to list (likely will be the textual folder itself)

**Comment by 1ace** [comment]
Actually `examples/code_browser.py` already covers the use of `DirectoryTree`, so I've replaced everything in this PR with just deleting that code :upside_down_face:

**Review by UriyaHarpeness — APPROVED** [review]

**Review by davep — APPROVED** [review]

**Pull request merged**
