### PR TITLE
Move the Textual FAQ into the main docs

### PR DESCRIPTION
**Pull request by davep**
Implements #3068.

### CODE REVIEW

**Review by rodrigogiraoserrao — COMMENTED** [review]
Don't we need to add `faqtory` to the (dev) dependencies of `Textual`, then?

**Comment by davep** [comment]
Good call; I had thought it was.

**Review by willmcgugan — APPROVED** [review]
Nice

**Comment by davep** [comment]
I just realised something: rather than have the two different link IDs floating around, I dropped faqtory's slugs from the generated FAQ and leaned into mkdocs-materials' IDs generated from the headers; but now I think about it faqtory and mkdocs-material might not slug the same.

I'll make an issue to double-check this tomorrow and I might have to add the faqtory slugs back and we'll just accept the duplication of effort in the page.

**Comment by willmcgugan** [comment]
Good point!

**Comment by willmcgugan** [comment]
I'm open to modifying the slug generation in FAQtory to match.

**Pull request merged**
