### PR TITLE
Strip text

### PR DESCRIPTION
**Pull request by willmcgugan**
Fixes https://github.com/Textualize/textual/issues/1620

### CODE REVIEW

**Review by darrenburns — APPROVED** [review]

**Review by davep — APPROVED** [review]

**Comment by ofek** [comment]
Nice! Is this how I would do it? I'm getting an empty string:

```python
''.join(segment.text for segment in text_log.render_lines(terminal_region))
```

**Comment by willmcgugan** [comment]
Try 

```python
''.join(line.text for line in text_log.lines)
```

That will give you the content prior to rendering. You want to avoid rendering the lines as the output depends on the dimensions of the terminal.

**Comment by willmcgugan** [comment]
If it is for testing though. You might want to consider snapshot tests. There are examples in our tests. At some point we will make those more easily accessible for other projects. We've found them to be fantastic for catching render related bugs.

**Comment by ofek** [comment]
That works now thank you! I will look into snapshot tests, that sounds very useful to be able to track changes to actual images 😮

**Pull request merged**
