### PR TITLE
Remove unused import of MounrError in app.py

### PR DESCRIPTION
**Pull request by davep**
Noticed while passing by.

### CODE REVIEW

**Comment by rodrigogiraoserrao** [comment]
Does this break the docstrings? A couple of them mention `MountError` and automatic linking may or may not depend on this `MountError` having been imported or not.

**Comment by davep** [comment]
I've never seen a Python doc system that's resolves linking that way; [and looking at our currently-published docs the one we use doesn't](https://textual.textualize.io/api/app/#textual.app.App.mount_all).

**Comment by rodrigogiraoserrao** [comment]
Great, then! I was just afraid something might break, but looks like it won't :)

**Review by rodrigogiraoserrao — APPROVED** [review]

**Comment by davep** [comment]
It does raise the question though: why do our docs link `Widget` but not `MountError` -- my wild guess is it's about what's in the docs? I might add an issue to think about checking on that at some point.

**Pull request merged**
