### PR TITLE
Sensible default key displays + allow users to override key displays at the `App` level

### PR DESCRIPTION
**Pull request by darrenburns**
**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- [x] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

Example output from snapshot test in which user-land app overrides some stuff, and question mark comes from Textual defaults.

image

### CODE REVIEW

**Review by davep — APPROVED** [review]

**Comment by aaronst** [comment]
Nice!

**Comment by willmcgugan** [comment]
Looks good. Is `^q` a fairly standard convention then?

**Review by willmcgugan — APPROVED** [review]

**Comment by davep** [comment]
> Looks good. Is `^q` a fairly standard convention then?

(Chiming in from the older days...) I'd absolutely read ^q as "control Q", it's been a convention as long as I've known.

**Comment by darrenburns** [comment]
Note that this PR will not make the `^` appear in the footer - that's just what I done in my test of the user overrides. Textual will still show CTRL+Q.

**Pull request merged**
