### PR TITLE
Detect non widgets

### PR DESCRIPTION
**Pull request by holdenweb**
**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- [x] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

I've been dogged by an `AttributeError` that occurs when trying to mount non-widgets (either directly, or because I've omitted the call to `Widget__init__()`), that points out a particular item has no `id`, so I added a message that should catch both cases. You may find better wording for the message.

Impact on speed should be zero, as the code only executes of a fatal error.

### CODE REVIEW

**Comment by davep** [comment]
There is a later check for the object being a widget, which will raise an `AppError`. For example, this:

```python
from dataclasses import dataclass

from textual.app import App, ComposeResult

@dataclass
class NotAWidget:
    id: str = ""

class MountNonWidgetApp(App[None]):

    def compose(self) -> ComposeResult:
        yield NotAWidget()

if __name__ == "__main__":
    MountNonWidgetApp().run()
```

results in this:

```
AppError: Can't register NotAWidget(id=''); expected a Widget instance
```

I sense the error raised here should match. Moreover, the existing check that the object is a widget could be used anyway, and so potentially the change could be:

```python
        try:
            ids_to_mount = [widget.id for widget in widgets if widget.id is not None]
        except AttributeError:
            ids_to_mount = []
```

In other words the lack of an ID would be a pass but then the "not a `Widget` instance" logic would catch this anyway.

However, neither of these approaches would seem to clarify the situation of failing to call `super().__init__()` in an actual `Widget` instance as the `id` property would be missing while at the same time it could be an instance of a widget that failed to have it.

Perhaps the ultimate improvement here would be in `App._register`, along with the check that the widget is a `Widget` instance, it also then goes on to check if the `Widget` has an `id` property and raises an `AppError` suggesting `__init__()` may have been overridden while `super().__init__()` might not have been called.

**Comment by holdenweb** [comment]
I've persisted with updating the PR, but it sounds as though your greater intimacy with the source has come up with more appropriate actions. Would you like me to take a look to see what the necessary changes to `App._register` might look like?

**Comment by holdenweb** [comment]
Hmmm ... it seems that Widget subclasses _are_ assigned an `id` somewhere. Perhaps the "no id" error was caused by passing a class instead of an instance of the class, probably a less frequent occurrence. Because subclasses aren't instances this case is already caught by the existing `_register()` code and so the only change required would seem to be the suppression of the `AttributeError` as you suggested above. The message could, perhaps, be improved, and perhaps the code could raise a `WidgetError` or `TypeError` rather than `AppError`, but the essential change is done.

**Comment by willmcgugan** [comment]
Thanks @holdenweb This was a good opportunity to improve DX.

Closing in favour of https://github.com/Textualize/textual/pull/3780

**Pull request closed without merging**
