### PR TITLE
Fix up/down key ansi sequences.

### LINKED ISSUE #2223: (Shift/Ctrl)+Alt+Up/Down are reversed
1. Run `textual keys` in xterm
2. Press `ctrl-alt-Up`, see this instead:
```
Key(key='escape', character=None, name='escape', is_printable=False, aliases=['escape', 'ctrl+left_square_brace'])                                                                                                                                                                                                             
Key(key='ctrl+down', character=None, name='ctrl_down', is_printable=False)
```
3. Press `alt-shift-Down`:
```
Key(key='escape', character=None, name='escape', is_printable=False, aliases=['escape', 'ctrl+left_square_brace'])                                                                                                                                                                                                             
Key(key='shift+up', character=None, name='shift_up', is_printable=False)                                                                                                                                                                                                                                                       
```
4. Notice that anytime `alt`/`meta` is combined with another modifier, `up`/`down` are reversed


# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.18.0 |
| Rich    | 13.3.3 |

## Python

| Name           | Value                                           |
|----------------|-------------------------------------------------|
| Version        | 3.11.2                                          |
| Implementation | CPython                                         |
| Compiler       | GCC 12.2.0                                      |
| Executable     | ~/textual/venv/bin/python |

## Operating System

| Name    | Value                                              |
|---------|----------------------------------------------------|
| System  | Linux                                              |
| Release | 6.1.0-2-amd64                                      |
| Version | `#1` SMP PREEMPT_DYNAMIC Debian 6.1.7-1 (2023-01-18) |

## Terminal

| Name                 | Value          |
|----------------------|----------------|
| Terminal Application | *Unknown*      |
| TERM                 | xterm-256color |
| COLORTERM            | *Not set*      |
| FORCE_COLOR          | *Not set*      |
| NO_COLOR             | *Not set*      |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=319, height=90 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 319                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 90                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

### PR DESCRIPTION
**Pull request by rodrigogiraoserrao**
This will close #2223.

Relevant comments: [my reply to OP](https://github.com/Textualize/textual/issues/2223\#issuecomment-1505512300) and [the OP's reply](https://github.com/Textualize/textual/issues/2223\#issuecomment-1506764562).
I just reordered some suspicious bindings with Up/Down which were inconsistent with all the other sequences.

I couldn't reproduce the bug locally and I'm essentially trusting the OP on this one.
I feel comfortable with the PR, though.

### CODE REVIEW

**Comment by willmcgugan** [comment]
Shift + up/down works on iTerm. If you've swapped them, aren't they going to break on macOS?

Have you tried these key combinations on other terminals? Gnome terminal + Windows terminal.

**Comment by rodrigogiraoserrao** [comment]
> Shift + up/down works on iTerm. If you've swapped them, aren't they going to break on macOS?
> 
> Have you tried these key combinations on other terminals? Gnome terminal + Windows terminal.

They didn't break on macOS.
Furthermore, the key bindings were also swapped in the Gnome terminal and now they are correct.
Couldn't test on Windows.

**Comment by willmcgugan** [comment]
I'm confused.

ctrl+shift+up / down works on macOS. How can you swap them, and they still work?

**Comment by rodrigogiraoserrao** [comment]
I didn't swap _all_ occurrences of Up/Down keys, right? Only some.

E.g., for Ctrl + Shift + Up that _was_ working before this PR and still is working, that's because Ctrl + Shift + Up was probably the escape sequence `"\x1b[1;6A"`, which I didn't touch:

https://github.com/Textualize/textual/blob/c8ecd26234b1fbf9f5df69310162afb2991fa48f/src/textual/_ansi_sequences.py#L236

In fact, if you look at the git blame, the line I just linked to was also swapped with the Down key and Darren fixed it 11 months ago.

This PR just fixes the remaining swaps.

**Review by willmcgugan — APPROVED** [review]

**Pull request merged**
