### PR TITLE
Prevent scrollbar rules from being ignored

### PR DESCRIPTION
**Pull request by rodrigogiraoserrao**
**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- ~[x] Updated documentation~
- [x] Updated CHANGELOG.md (where appropriate)

### CODE REVIEW

**Comment by willmcgugan** [comment]
Looks like the scrollbars have a rather sickly yellow color. I'm guessing because colors that were previously ignored are now updated?

You might need to change the defaults, to restore the original look.

Screenshot 2023-01-05 at 11 48 34

**Comment by rodrigogiraoserrao** [comment]
@willmcgugan I only get that “sicklish” tone when scrollbars are being hovered and I thought that was the default styling for `scrollbar-color-hover` (which was being ignored).

Here is a screenshot: on the left, I have my mouse over the scrollbar (which also means that I **do not** have my mouse over the scrollbar on the right).

Screenshot at Jan 05 12-04-06

What color would you prefer, instead, for `scrollbar-color-hover`?

**Comment by willmcgugan** [comment]
Same color as before this update, which I believe didn't change the scrollbar thumb at all...

**Comment by rodrigogiraoserrao** [comment]
Yes, before this update the scrollbar thumb wasn't updated when the scrollbar was hovered.

Upon hovering a scrollbar, do we want the default `scrollbar-color-hover` to _match_ `scrollbar-color` or do we want it to be explicitly that specific shade of blue?

**Comment by willmcgugan** [comment]
Set it to the same shade should be fine. It still allows custom CSS to override it if desired.

**Comment by willmcgugan** [comment]
Looks good!

**Review by willmcgugan — APPROVED** [review]

**Pull request merged**
