### PR TITLE
allow empty css variables

### LINKED ISSUE #1849: Allow for empty CSS variable definitions
Consider the following CSS snippets:

 1.
```sass
$x: 
* {
    background: red;
}
```

2.
```sass
$x:
* {
    background: $x;
}
```

3.
```sass
* {
    background: red;
}
$x:
```

All three should work with the following behaviour:
 - an empty variable definition is allowed; and
 - setting a style to an empty variable should unset that style.

For example, 2. should unset the background of all widgets.

As of now, 2. and 3. can't be parsed.
2. raises an error regarding an undefined variable and 3. raises an `AttributeError` inside `substitute_references` in `parse.py`.

### PR DESCRIPTION
**Pull request by zormit**
fixes #1849

**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- [x] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

Co-authored-by: @eliasdorneles

### CODE REVIEW

**Review by rodrigogiraoserrao — COMMENTED** [review]
Looking good!

I was looking at the `if: ... elif: ... elif: ...` and I see we are now doing `variables.setdefault` in pretty much all of the branches that look interesting.
Is it possible that we can call `setdefault` earlier and then do regular dictionary assignment?

I'm not sure we can & if we can, not sure it'll help.
But I'd like you to give it some thought, if possible.

Thanks!

**Review by rodrigogiraoserrao — APPROVED** [review]
Looks good to me! 🚀

**Review by rodrigogiraoserrao — APPROVED** [review]

**Comment by rodrigogiraoserrao** [comment]
@willmcgugan this is ready for you to take a look!

**Review by willmcgugan — APPROVED** [review]
LGTM!

**Pull request merged**
