### PR TITLE
Add panel Border type to docs

### PR DESCRIPTION
**Pull request by AkintolaRichard**
* Add panel border description
* Add Label with panel border to Grid
* Add style for panel id and change grid-size from 3 5 to 4 4

issues #3978

**Please review the following checklist.**

- [ ] Docstrings on all new or modified functions / classes 
- [ ] Updated documentation
- [ ] Updated CHANGELOG.md (where appropriate)

### CODE REVIEW

**Review by rodrigogiraoserrao — CHANGES_REQUESTED** [review]
Hey @AkintolaRichard, thanks for your PR!
Before I can merge it, would you mind going back to the three files you modified and keeping things in alphabetical order?
This applies to the table, the `Label`s in the example app, and the `#panel` TCSS.

Thanks!

**Comment by AkintolaRichard** [comment]
Okay, I will do that right away. Can I also try rebasing?

**Comment by rodrigogiraoserrao** [comment]
Sure. Just ping me after the changes so I can take another look at the PR, please.

**Comment by AkintolaRichard** [comment]
Hi @rodrigogiraoserrao, I have made the arrangement. I almost miss with the rebasing.

**Review by rodrigogiraoserrao — APPROVED** [review]

**Comment by AkintolaRichard** [comment]
Thank you very much @rodrigogiraoserrao,  I am grateful for your guidance and your patience.

**Comment by rodrigogiraoserrao** [comment]
No problem. 🚀

**Comment by rodrigogiraoserrao** [comment]
At the moment, no particular issues come to mind as good issues for you to tackle but feel free to look around for something you want to try and remember you can always get help in the Textual Discord server https://discord.gg/Enf6Z3qhVr.

**Comment by AkintolaRichard** [comment]
Thank you once again, how can I tag you on the Discord Server.

**Comment by rodrigogiraoserrao** [comment]
You can use `@rodrigogiraoserrao` to tag me there but you can also just ask your questions there and the first available person will lend you a hand.
If/when you ask questions, if you're asking Qs about Textual don't forget to look in the docs as well.

**Pull request merged**
