### PR TITLE
Keep state when reloading tree.

### LINKED ISSUE #3574: Refreshing the DirectoryTree without resetting the selected node.
We are really enjoying using the textual for our project and are impressed with its ease of use and powerful features.

Currently we have a DirectoryTree widget that is integral to the project. If a file or folder is deleted through the filesystem (i.e. not through our application), we would like to ensure the DirectoryTree in the app is refreshed to reflect this.

Currently the `reload` function serves this purpose, and it is sufficient for us to call every now and then (e.g. when a file or folder is clicked on the DirectoryTree). However, the only problem is that the `reload` function moves the currently selected folder back to the root folder. Is there a way to call `reload()` without changing the currently selected folder, and avoid having the dropdown structure of entire tree reset?

### PR DESCRIPTION
**Pull request by rodrigogiraoserrao**
**Please review the following checklist.**

- [ ] Docstrings on all new or modified functions / classes 
- [ ] Updated documentation
- [ ] Updated CHANGELOG.md (where appropriate)

This will fix #3574

### CODE REVIEW

**Comment by willmcgugan** [comment]
Parking this for now. Would like to tackle it myself, at least enough to understand the issues involved.

**Comment by JoeZiminski** [comment]
Hey @willmcgugan @rodrigogiraoserrao thanks a lot for looking into this. I am definately happy to help contribute if it could be useful, it would be great to have this for a feature we are working on.

**Comment by rodrigogiraoserrao** [comment]
It's @willmcgugan's call; I was working on this but was asked to stop.

**Comment by rodrigogiraoserrao** [comment]
Closed in favour of the work that will come out of #4056.

**Pull request closed without merging**
