### PR TITLE
Document compound widgets.

### PR DESCRIPTION
**Pull request by rodrigogiraoserrao**
I think I got a bit carried away and used a tone similar to the one in my blog.
Let me know if you think the style is off.

Follow-up: one example app depends on the resolution of #1815 to display 100% correctly.

### CODE REVIEW

**Comment by willmcgugan** [comment]
This isn't quite what I was looking for. My fault, I should have worked with you a but more closely. 

The guide needs to fairly concisely convey key concepts, and (as you said) the tone here is more long-form tutorial.

I think I might take over this one.

**Comment by rodrigogiraoserrao** [comment]
No worries. What if I make this a blog post and strip it down to the bare essentials for the guide?

**Comment by willmcgugan** [comment]
Hold off for now. Still planning.

**Comment by rodrigogiraoserrao** [comment]
> Hold off for now. Still planning.

Holding off. I'm just saying I'd like an opportunity to fix this. 😅

**Comment by willmcgugan** [comment]
Closing this for house keeping. Feel free to publish in on your blog.

**Pull request closed without merging**
