### PR TITLE
Infer a default value for datatable column and row keys

### PR DESCRIPTION
**Pull request by whilb**
This small PR more closely matches what the docstrings of these functions claim to do.

- [x] Docstrings on all new or modified functions / classes 
- [x] Updated documentation
- [ ] Updated CHANGELOG.md (where appropriate)

### CODE REVIEW

**Comment by willmcgugan** [comment]
@darrenburns can you review please?

**Comment by darrenburns** [comment]
Thanks for the PR, but I think there's a misunderstanding here - the docstring says a key will be generated for you if you don't supply one.

This already happens - if you don't supply a key, one is created internally and returned from the method.

You can then use this key to refer to the column/row in the future regardless of what sorting has been applied to the DataTable.

Let us know if you were seeing behaviour inconsistent with this @whilb.

**Comment by whilb** [comment]
I see that the `add_columns` and `add_rows` methods return lists of ColumnKey and RowKey objects respectively, but the current behavior I see appears incorrect or non-intuitive. I would expect that the `value` attribute of each ColumnKey or RowKey object to be something other than None -- they are clearly their own objects, but I think they should include a smarter `value` attribute.



I've taken the example and included some input from running the file against the DataTable at textual==0.35.1 and a


```python
#!python3
# -*- coding: utf-8 -*-
from textual.app import App, ComposeResult
from textual.widgets import DataTable

ROWS = [
    ("lane", "swimmer", "country", "time"),
    (4, "Joseph Schooling", "Singapore", 50.39),
    (2, "Michael Phelps", "United States", 51.14),
    (5, "Chad le Clos", "South Africa", 51.14),
    (6, "László Cseh", "Hungary", 51.14),
    (3, "Li Zhuhao", "China", 51.26),
    (8, "Mehdy Metella", "France", 51.58),
    (7, "Tom Shields", "United States", 51.73),
    (1, "Aleksandr Sadovnikov", "Russia", 51.84),
    (10, "Darren Burns", "Scotland", 51.84),
]


class TableApp(App):
    def compose(self) -> ComposeResult:
        yield DataTable()

    def on_mount(self) -> None:
        table = self.query_one(DataTable)
        keys = table.add_columns(*ROWS[0])
        keyrep = [repr(key) for key in keys]
        rkeys = table.add_rows(ROWS[1:])
        assert False


app = TableApp()
if __name__ == "__main__":
    app.run()
```

Textual/main 0.35.1
```
(textual) wbutler@wbutler-z2:~/work/textual$ python datatable_poc.py
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ /home/wbutler/work/textual/datatable_poc.py:29 in on_mount                                                                                                                                                                                                                  │
│                                                                                                                                                                                                                                                                             │
│   26 │   │   keys = table.add_columns(*ROWS[0])                                                                                                                                                                                                                             │
│   27 │   │   keyrep = [repr(key) for key in keys]                                                                                                                                                                                                                           │
│   28 │   │   rkeys = table.add_rows(ROWS[1:])                                                                                                                                                                                                                               │
│ ❱ 29 │   │   assert False                                                                                                                                                                                                                                                   │
│   30                                                                                                                                                                                                                                                                        │
│   31                                                                                                                                                                                                                                                                        │
│   32 app = TableApp()                                                                                                                                                                                                                                                       │
│                                                                                                                                                                                                                                                                             │
│ ╭─────────────────────────────────────────────────────────────────────────────────────────── locals ────────────────────────────────────────────────────────────────────────────────────────────╮                                                                           │
│ │ keyrep = [                                                                                                                                                                                    │                                                                           │
│ │          │   '<textual.widgets._data_table.ColumnKey object at 0x7f287b1bead0>',                                                                                                              │                                                                           │
│ │          │   '<textual.widgets._data_table.ColumnKey object at 0x7f287970e0d0>',                                                                                                              │                                                                           │
│ │          │   '<textual.widgets._data_table.ColumnKey object at 0x7f2879708350>',                                                                                                              │                                                                           │
│ │          │   '<textual.widgets._data_table.ColumnKey object at 0x7f2879708590>'                                                                                                               │                                                                           │
│ │          ]                                                                                                                                                                                    │                                                                           │
│ │   keys = [ColumnKey(value=None), ColumnKey(value=None), ColumnKey(value=None), ColumnKey(value=None)]                                                                                         │                                                                           │
│ │  rkeys = [RowKey(value=None), RowKey(value=None), RowKey(value=None), RowKey(value=None), RowKey(value=None), RowKey(value=None), RowKey(value=None), RowKey(value=None), RowKey(value=None)] │                                                                           │
│ │   self = TableApp(title='TableApp', classes={'-dark-mode'})                                                                                                                                   │                                                                           │
│ │  table = DataTable()                                                                                                                                                                          │                                                                           │
│ ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                           │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError
```

whilb:wgb/default-datatable-keys
```
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ \datatable_test.py:29 in on_mount
│
│   26 │   │   keys = table.add_columns(*ROWS[0])                                               ╭────────────────────────────────────────────────────────────────────────────── locals ───────────────────────────────────────────────────────────────────────────────╮
│   27 │   │   keyrep = [repr(key) for key in keys]                                             │ keyrep = [                                                                                                                                                          │
│   28 │   │   rkeys = table.add_rows(ROWS[1:])                                                 │          │   '<textual.widgets._data_table.ColumnKey object at 0x0000026422D43D48>',                                                                                │
│ ❱ 29 │   │   assert False                                                                     │          │   '<textual.widgets._data_table.ColumnKey object at 0x0000026422D43E08>',                                                                                │
│   30                                                                                          │          │   '<textual.widgets._data_table.ColumnKey object at 0x0000026422D45A08>',                                                                                │
│   31                                                                                          │          │   '<textual.widgets._data_table.ColumnKey object at 0x0000026422D45C88>'                                                                                 │
│   32 app = TableApp()                                                                         │          ]                                                                                                                                                          │
│                                                                                               │   keys = [ColumnKey(value='lane'), ColumnKey(value='swimmer'), ColumnKey(value='country'), ColumnKey(value='time')]                                                 │
│                                                                                               │  rkeys = [RowKey(value=4), RowKey(value=2), RowKey(value=5), RowKey(value=6), RowKey(value=3), RowKey(value=8), RowKey(value=7), RowKey(value=1), RowKey(value=10)] │
│                                                                                               │   self = TableApp(title='TableApp', classes={'-dark-mode'})                                                                                                         │
│                                                                                               │  table = DataTable()                                                                                                                                                │
│                                                                                               ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
AssertionError
```

This None value is noticed in things like message handlers
```
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ /home/wbutler/work/textual/datatable_test.py:36 in handle_cell_highlight                                                                                                                                                                                                    │
│                                                                                                                                                                                                                                                                             │
│   33 │                                                                                        ╭───────────────────────────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────────────────────────╮                  │
│   34 │   @on(DataTable.CellHighlighted)                                                       │ event = CellHighlighted(value=4, coordinate=Coordinate(row=0, column=0), cell_key=CellKey(row_key=RowKey(value=None), column_key=ColumnKey(value=None))) │                  │
│   35 │   def handle_cell_highlight(self, event):                                              │  self = TableApp(title='TableApp', classes={'-dark-mode'})                                                                                               │                  │
│ ❱ 36 │   │   assert False                                                                     ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                  │
│   37                                                                                                                                                                                                                                                                        │
│   38                                                                                                                                                                                                                                                                        │
│   39 app = TableApp()                                                                                                                                                                                                                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError
```


Am I interpreting the docstring correctly and the `value` attribute of a `...Key` object should be None if not specified?

**Comment by darrenburns** [comment]
The value of a RowKey or ColumnKey should be None if it's not specified, yeah. I think the `repr` is probably causing some confusion here - because the reprs look the same so you might think the keys are the same (but they're not - they hash uniquely).

**Comment by whilb** [comment]
That makes sense, thank you for clarifying!

**Pull request closed without merging**
