### PR TITLE
button tweak

### PR DESCRIPTION
**Pull request by willmcgugan**
Makes buttons a little more flexible. They now have auto height, and a padding will be applied to all lines.

### CODE REVIEW

**Review by davep — COMMENTED** [review]
I sense this needs a nice big juicy "breaking change" entry in the CHANGELOG given it'll have knock-on effects for layouts in applications. With this code:

```python
from textual.app import App, ComposeResult
from textual.widgets import Button

class ButtonsApp(App[None]):

    def compose(self) -> ComposeResult:
        for n in range(5):
            yield Button(f"Button {n}\n" * (n+1))

if __name__ == "__main__":
    ButtonsApp().run()
```

going from this:

Screenshot 2023-10-15 at 17 49 15

to this:

Screenshot 2023-10-15 at 17 49 36

**Comment by willmcgugan** [comment]
Why would anyone have buttons with new lines that don't display?

**Comment by davep** [comment]
Accidentally doing it would be the most obvious cause; or having observed only the first line shows and unfortunately relying on that. Given this would cause visible layout changes it seems prudent to me to give everyone a heads up in the document intended for that.

**Comment by willmcgugan** [comment]
I've added a changelog, but I don't see that as a breaking change. A visual change, certainly, but we've not marked such changes as breaking in the past.

**Review by davep — APPROVED** [review]

**Pull request merged**
