### PR TITLE
datatable: style datatable--cursor for focus changes

### PR DESCRIPTION
**Pull request by shuckc**
**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- [ ] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

### CODE REVIEW

**Comment by rodrigogiraoserrao** [comment]
Hey @shuckc, thanks for opening this PR.
Please consider taking a look at the contributing guide (CONTRIBUTING.md in the repo) and, in particular, see how to run the tests and how to update the snapshot tests.

Additionally, consider adding screenshots of the before/after that your CSS change introduces in your PR comment and a sentence or two on why you are proposing that we change the default CSS for the data table.

This will make sure we fully understand the scope and impact of your changes when reviewing the PR.

**Comment by shuckc** [comment]
Here is the result of the visual diff. Since the `DataTable` does not have focus, the highlighted cell is not rendered in yellow. I have committed the updated test output. 

image

**Comment by rodrigogiraoserrao** [comment]
I see, thanks for the extra context.
I'll ask someone else to double-check this stylistic change!

**Review by rodrigogiraoserrao — APPROVED** [review]

**Comment by shuckc** [comment]
Sure - I've got the CSS changes already.  have two DataTables displayed at once, so needing to know which has focus was important.

**Pull request closed without merging**
