### PR TITLE
Tick off `TextArea`-related items on the roadmap

### PR DESCRIPTION
**Pull request by davep**
Not actually quite sure what indentation guides means here, so I'm leaving that alone.

### CODE REVIEW

**Comment by darrenburns** [comment]
Indentation guides are the vertical dim guides drawn at each tab stop to make it easy to align things vertically. 

These lines:

image

**Comment by davep** [comment]
Ahh, cool, did wonder. Presumably that isn't in yet?

**Comment by darrenburns** [comment]
@davep Correct

**Comment by darrenburns** [comment]
Not sure we can tick off "smart features for various languages". Not actually sure what that's referring to. Maybe things like automatically indenting when you take a newline, automatically closing brackets, automatically create bullet points in lists in Markdown etc.

**Pull request merged**
