### PR TITLE
Fix select

### PR DESCRIPTION
**Pull request by willmcgugan**
Fixes https://github.com/Textualize/textual/issues/4489

### CODE REVIEW

**Comment by willmcgugan** [comment]
@TomJGooding I think this is the fix...

**Comment by TomJGooding** [comment]
Wouldn't this introduce a new issue where the overlay would stay expanded if you clicked to focus another widget?

**Comment by willmcgugan** [comment]
You're absolutely right. Pushed an alternative fix, which doesn't break hiding the drop down on blur.

**Comment by TomJGooding** [comment]
This seems to have done the trick after from a quick test!

Just for my own knowledge, is this suppression of the click really only required because the overlay concept doesn't play nicely with focusing?

**Comment by willmcgugan** [comment]
> Just for my own knowledge, is this suppression of the click really only required because the 'overlay' concept doesn't play nicely with how the focus is handled?

Pretty much. The interaction with click / blur was proving to be difficult to unpick. I suspect it could be done much simpler with pure CSS, but I didn't get that far.

**Pull request merged**
