### PR TITLE
fix: handle missing tree-sitter-language binaries

### PR DESCRIPTION
**Pull request by tconbeer**
**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- [x] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

Closes https://github.com/Textualize/textual/issues/4045

I don't think new documentation is necessary. Happy to provide if you disagree.

### CODE REVIEW

**Comment by davep** [comment]
I've not looked to see if it is affected or not, but note that #3933 is close to being merged and has a *lot* of changes to all things `TextArea`; so keep in mind that this might get held back for a wee while until that's merged, or perhaps run this by @darrenburns as a small addition there (there is also a followup PR to come that will make some other QoL changes to `TextArea`, so it might make sense that it rolls into that).

**Comment by tconbeer** [comment]
Thanks, Dave. I'm fine if this waits on the other PR, although a quick scan through the changes didn't reveal any obvious conflicts

**Comment by darrenburns** [comment]
Strange - this doesn't happen for me if I uninstall `tree-sitter-languages`. The functionality is supposed to degrade with a logged warning in the console:

image

The intention is that the constructor of `SyntaxAwareDocument` shouldn't even be called if `tree-sitter-languages` is unavailable (I would expect `TREE_SITTER` to be `False` on the line shown below, which results in a plain `Document` being created).

https://github.com/Textualize/textual/blob/23735cdc341d07d27cece6e1c94ac27a9b155609/src/textual/widgets/_text_area.py#L625

https://github.com/Textualize/textual/blob/bbde62fc5751a03d5fe6e96ee0da469308f16295/src/textual/_tree_sitter.py#L10

So it seems the binaries can be installed and then fail in some environments?

I don't understand the root cause, but I think handling this error is still a good call regardless.

**Comment by darrenburns** [comment]
Ah, I think I understand now. So the `tree-sitter-languages` package on Conda is broken such that the package is available, but doesn't actually contain the required binaries... I think? So, installation of `tree-sitter-languages` succeeds, but it's essentially an empty package 😄

**Review by darrenburns — APPROVED** [review]

**Comment by willmcgugan** [comment]
Thanks @tconbeer !

**Pull request merged**
