### PR TITLE
Support custom sort functions in 'DataTable'

### PR DESCRIPTION
**Pull request by Alphix**
This is somewhat related to issue #2261

**Please review the following checklist.**

- [x] Docstrings on all new or modified functions / classes 
- [x] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

### CODE REVIEW

**Comment by willmcgugan** [comment]
@darrenburns Thoughts on this?

**Comment by darrenburns** [comment]
I like the idea but I'm wondering if sorting by key should be a separate method. With the approach in this PR,  "column" and "key" have an awkward dependency on each other. If you supply both, it's unclear what will happen without reading the docs.

**Comment by Alphix** [comment]
> I like the idea but I'm wondering if sorting by key should be a separate method. With the approach in this PR, "column" and "key" have an awkward dependency on each other. If you supply both, it's unclear what will happen without reading the docs.

I could change the PR to follow that approach. I guess the alternative method (`sort_custom()`?) would have to duplicate most of the body of the current `sort()` method, but that's only 9 lines of duplication...

**Comment by darrenburns** [comment]
Another option could be that the `sort` method signature is updated from

```python
    def sort(
        self,
        *columns: ColumnKey | str,
        reverse: bool = False,
    ) -> Self
```

To something like...

```python

    def sort(
        self,
        by: Iterable[ColumnKey | str] | Callable,
        reverse: bool = False,
    ) -> Self
```

So you could either supply an iterable of columns _or_ you can supply a function to `sort`.

**Comment by TomJGooding** [comment]
I stumbled across this open PR looking for something else. 

Sorting a `DataTable` with a custom function was added in Textual v0.41.0. - https://textual.textualize.io/widgets/data_table/#sorting

**Comment by Alphix** [comment]
> I stumbled across this open PR looking for something else.
> 
> Sorting a `DataTable` with a custom function was added in Textual v0.41.0. - https://textual.textualize.io/widgets/data_table/#sorting

Indeed, I'll close this...

**Pull request closed without merging**
