### PR TITLE
Handle subscripted generics in query selector

### PR DESCRIPTION
**Pull request by davetapley**
Same as #3805 but change my branch off `main`

### CODE REVIEW

**Comment by rodrigogiraoserrao** [comment]
Hey Dave, thanks for the PR.
Would you mind adding a couple of regression tests? 🙌

**Comment by davetapley** [comment]
@rodrigogiraoserrao I _can_ but it won't be pretty because:

The fix requires Python 3.9 (for https://peps.python.org/pep-0585/), but the tests also run on 3.8.

Note: #2867 is a hard crash anyway, so fix is _no worse_ than existing behavior on 3.8.

For tests can either:
1. Defer until 3.8 support is dropped (easiest)
2. Only run test on >= 3.9
3. Expect exception on 3.8, work on >= 3.9

Any preference?

**Comment by davetapley** [comment]
@rodrigogiraoserrao I was, but I didn't know about `skipif`, that makes it look quite easy 😁 
I'll get some tests in ASAP.

**Comment by willmcgugan** [comment]
Would I be correct in saying this wouldn't check the generic type, just the class?

i.e. the following would return all DataTable, not just float Datatables?

```python
self.query("*", "DataTable[float]")
```

**Comment by willmcgugan** [comment]
I don't think this would correctly restrict the query. i.e. `self.query(DataTable[float])` would return all datatables, not just tables of floats. If we can't guarantee that the runtime matches the types, then it's not really viable.

Closing for now, but let me know if I've misunderstood or there is another way to achieve this.

**Pull request closed without merging**
