### PR TITLE
fix: 'old example' -> old_example

### PR DESCRIPTION
**Pull request by Abdur-rahmaanJ**

### CODE REVIEW

**Comment by willmcgugan** [comment]
That entire directory is going to be deleted.

**Comment by Abdur-rahmaanJ** [comment]
@willmcgugan ok but in the meantime the space is tripping for contributors who want to view examples

**Comment by willmcgugan** [comment]
Tripping? In what way?

**Comment by Abdur-rahmaanJ** [comment]
@willmcgugan cd into old examples

**Comment by willmcgugan** [comment]
```
cd old\ examples/
```

or 

```
cd "old examples"
```

But regardless, the old examples don't work and will be removed very soon...

**Comment by willmcgugan** [comment]
Thanks anyway

**Comment by Abdur-rahmaanJ** [comment]
@willmcgugan Yes, they don't work. Yes you can but like people have to type twice as it is not expected.

**Pull request closed without merging**
