### PR TITLE
fix(footer): enable spacing between key and description

### LINKED ISSUE #4557: New `Footer` missing space between key and description
Originally discussed in #4555, it looks like the new `Footer` doesn't have any space between the key and the description, which doesn't look great if you've added a background style for the key.

```python
from textual.app import App, ComposeResult
from textual.widgets import ClassicFooter, Footer, Label


class FooterApp(App):
    BINDINGS = [("space", "switch_footer", "Switch Footer")]

    CSS = """
    Screen {
        align: center middle;
    }

    Footer {
        background: $accent;
    }

    Footer > FooterKey {
        background: $accent;
        color: $text;
        .footer-key--key {
            background: $accent-darken-2;
            color: $text;
        }
    }
    """

    footer_type = "classic"

    def compose(self) -> ComposeResult:
        yield Label(
            f"{self.footer_type.title()} Footer",
            id="footer-type-label",
        )
        yield ClassicFooter()

    def action_switch_footer(self) -> None:
        if self.footer_type == "classic":
            self.query_one(ClassicFooter).remove()
            self.mount(Footer())
            self.footer_type = "new"
        else:
            self.query_one(Footer).remove()
            self.mount(ClassicFooter())
            self.footer_type = "classic"

        self.query_one(Label).update(
            f"{self.footer_type.title()} Footer",
        )


if __name__ == "__main__":
    app = FooterApp()
    app.run()
```

### PR DESCRIPTION
**Pull request by TomJGooding**
This is my (second) attempt to fix #4557. It isn't pretty but I'm still not sure how this should be implemented. Perhaps I'm missing something obvious, but the fact that the Footer currently uses 'raw' spaces suggests adding padding might not be so simple?

**Please review the following checklist.**

- [ ] Docstrings on all new or modified functions / classes 
- [ ] Updated documentation
- [x] Updated CHANGELOG.md (where appropriate)

### CODE REVIEW

**Comment by TomJGooding** [comment]
I'm actually now wondering if this whole section should be adapted for CSS styling with padding and margins:

https://github.com/Textualize/textual/blob/e9ad400559c14645e56b7a98a467295c6817686b/src/textual/widgets/_footer.py#L91-L98

Maybe *something* like this. Rather than hardcoding `f" {key_display} "` on line 97, instead this could be defined using padding. The added space after the description could be defined using margin.

What do you think? 

```python
        label_text = Text.assemble(
            # Key display (with padding)
            (" " * key_padding.left, key_style),
            (key_display, key_style),
            (" " * key_padding.right, key_style),
            # Add spacing to right of the key
            (" " * key_margin.right),
            # Description display
            (description, description_style),
            # Add spacing to right of the description
            (" " * description_margin.right),
        )
```

**Comment by willmcgugan** [comment]
Seems reasonable. Although one thing to be aware of is that margins overlap. So the space between key and description should be the maximum of the two margins.

**Comment by TomJGooding** [comment]
Sorry also just to note after diving deeper into this: I spotted the 'default' footer uses a raw space after the description, whereas in the 'compact' style instead uses the grid gutter...?

https://github.com/Textualize/textual/blob/4a40027ef6406a46866574af20a4b1d7c358bc78/src/textual/widgets/_footer.py#L123-L125

**Comment by TomJGooding** [comment]
I've gone ahead and changed that hardcoded space to the `grid-gutter'. This caused multiple snapshot tests to fail despite no visual changes (example below) so I updated the snapshots. If you're happy to merge this PR, I wonder if worth giving projects like memray a heads up on this given the spate of other changes to the footer.

image

**Comment by TomJGooding** [comment]
I've reverted the commit that updated the snapshot tests. I wanted to check if #4675 might account now for these changes but unfortunately not.

**Review by darrenburns — CHANGES_REQUESTED** [review]
Seems like there's a rendering issue - see my other comment. Would be good to investigate this before merging.

**Comment by TomJGooding** [comment]
Good catch, thanks Darren! I might be wrong but is the fix as simple as adding `layout=True` to the reactive?

**Comment by darrenburns** [comment]
@TomJGooding Sadly that doesn't seem to fix it 😢

**Comment by TomJGooding** [comment]
Sorry to clarify, I mean the `compact` reactive in the `FooterKey`(not the Footer). This seems to fix the example above from a quick test.

**Comment by TomJGooding** [comment]
Thanks Darren, good catch again as I hadn't spotted I'd changed the hover styling.

I expect that is why the "the 'default' footer uses a raw space after the description, whereas in the 'compact' style instead uses the grid gutter" then!

**Comment by darrenburns** [comment]
Yeah I'm guessing that's why. I tried playing around with the CSS for a few minutes and seem to get every combination of spacing apart from the one I'm aiming for 😂

**Comment by TomJGooding** [comment]
Thanks again Darren for catching these issues, in hindsight I probably should have added more snapshot tests before making changes.

I will double-check with a fresh head tomorrow, but hopefully these are resolved with my latest commits.

**Review by darrenburns — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
